### ISSUE TITLE
Failed to build corodva projects with version 0.6.1

### ISSUE THREAD

**Issue by qiuzhong** [01org/cordova-plugin-ocf#3]
For version 0.6.1, the plugin.xml specifies the iotivity patch aar file <code>iotivity-1.1.1.patched.aar</code>
while the one in libs directory is <code>iotivity-1.1.1-patched.aar</code>

Since 0.6.1 version is not released to npmjs repository, fetching it from npm failed.
I tried adding this plugin manually.
But it failed to add this plugin to the [smart-home-control](https://github.com/siovene/smart-home-control) project via github manually. 
```
$ cordova plugin add https://github.com/01org/cordova-plugin-ocf
...
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-ocf':CordovaError: Uh oh!
"/home/orange/01_qiuzhong/iot/smart-home-control/plugins/cordova-plugin-ocf/libs/iotivity-1.1.1.patched.aar" not found!
    at copyFile (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/lib/pluginHandlers.js:219:36)
    at handlers.resource-file.install (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/lib/pluginHandlers.js:74:13)
    at Object.ActionStack.process (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at /home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/Api.js:251:18
    at _fulfilled (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/node_modules/q/q.js:796:13)
    at /home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/cordova/node_modules/q/q.js:604:44
Error: Uh oh!
"/home/orange/01_qiuzhong/iot/smart-home-control/plugins/cordova-plugin-ocf/libs/iotivity-1.1.1.patched.aar" not found!
```
Same results if replace <code>cordova-plugin-ocf@0.6.1</code> with <code>https://github.com/01org/cordova-plugin-ocf</code> in package.json.

Tried to fix it by:
- Downloading the repository and renaming the aar file in libs to <code>iotivity-1.1.1.patched.aar</code>
- Adding this plugin locally. Then the plugin can be added to the [smart-home-control](https://github.com/siovene/smart-home-control) project successfully. But it still failed to build the project:
	```
	$ grunt run
	/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/src/OcfBackendIotivity.java:358: error: method does not override or implement a method from a supertype
		@Override
		^
	1 error
	:compileDebugJavaWithJavac FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':compileDebugJavaWithJavac'.
	> Compilation failed; see the compiler error output for details.

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

	Total time: 5.019 secs
	Error: /home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/gradlew: Command failed with exit code 1 Error output:
	Note: Some input files use or override a deprecated API.
	Note: Recompile with -Xlint:deprecation for details.
	Note: Some input files use or override a deprecated API.
	Note: Recompile with -Xlint:deprecation for details.
	/home/orange/01_qiuzhong/iot/smart-home-control/platforms/android/src/OcfBackendIotivity.java:358: error: method does not override or implement a method from a supertype
		@Override
		^
	1 error

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':compileDebugJavaWithJavac'.
	> Compilation failed; see the compiler error output for details.

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	```

**Comment by siovene** [comment]
Thanks, just fixed.
